spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:traininginsights}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

app:
  jwt:
    secret: ${TI_JWT_SECRET:dev-secret-change-me}
    expirationMillis: 86400000 # 24h
  uploadsDir: ${APP_UPLOADS_DIR:uploads}

# VAPID keys for Web Push notifications. Generate a keypair and set these values in your production
# environment (do NOT commit private key to source). Example generation can be done using the
# nl.martijndwars web-push library or external tools. If these are empty, push sending falls back to logging.
vapid:
  public: ${VAPID_PUBLIC:}
  private: ${VAPID_PRIVATE:}
  # Optional email/subject used in VAPID claims
  subject: ${VAPID_SUBJECT:mailto:admin@localhost}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha
    operationsSorter: method
  api-docs:
    enabled: true
